Boston Housing Dataset


Predicting Median value of owner-occupied homes

CRIM - per capita crime rate by town

ZN - proportion of residential land zoned for lots over 25,000 sq.ft.

INDUS - proportion of non-retail business acres per town.

CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)

NOX - nitric oxides concentration (parts per 10 million)

RM - average number of rooms per dwelling

AGE - proportion of owner-occupied units built prior to 1940

DIS - weighted distances to five Boston employment centres

RAD - index of accessibility to radial highways

TAX - full-value property-tax rate per $10,000

PTRATIO - pupil-teacher ratio by town

B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town

LSTAT - % lower status of the population

MEDV - Median value of owner-occupied homes in $1000's




Aim


To implement a linear regression with regularization via gradient descent. to implement gradient descent with Lp norm, for 3 different values of p in (1,2]

In [24]:
import pandas as pd

In [25]:
df=pd.read_csv('/content/boston.csv')
df.head()

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0,0.95577,0.0,8.14,0,0.538,6.047,88.8,4.4534,4,307.0,21.0,306.38,17.28,14.8
1,1,0.02875,28.0,15.04,0,0.464,6.211,28.9,3.6659,4,270.0,18.2,396.33,6.21,25.0
2,2,1.22358,0.0,19.58,0,0.605,6.943,97.4,1.8773,5,403.0,14.7,363.43,4.59,41.3
3,3,5.66637,0.0,18.10,0,0.740,6.219,100.0,2.0048,24,666.0,20.2,395.69,16.59,18.4
4,4,0.04544,0.0,3.24,0,0.460,6.144,32.2,5.8736,4,430.0,16.9,368.57,9.09,19.8

In [26]:
df.isnull().sum()

ID         0
CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [27]:
df.corr()

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
ID,1.000000,-0.009895,-0.037340,0.005167,-0.034274,-0.034631,0.061728,-0.031016,0.010385,-0.031669,-0.007460,0.056734,-0.030764,-0.019382,0.006956
CRIM,-0.009895,1.000000,-0.193548,0.409972,-0.060591,0.422635,-0.205928,0.353379,-0.376323,0.618538,0.577501,0.284967,-0.357581,0.442743,-0.393693
ZN,-0.037340,-0.193548,1.000000,-0.522218,-0.037318,-0.497638,0.290127,-0.554214,0.659949,-0.301067,-0.300221,-0.369974,0.161515,-0.402116,0.336805
INDUS,0.005167,0.409972,-0.522218,1.000000,0.075305,0.759132,-0.396865,0.631742,-0.695199,0.608088,0.731619,0.370383,-0.338007,0.624374,-0.502898
CHAS,-0.034274,-0.060591,-0.037318,0.075305,1.000000,0.084020,0.091267,0.083314,-0.102016,-0.023792,-0.045183,-0.137556,0.040732,-0.055326,0.182096
NOX,-0.034631,0.422635,-0.497638,0.759132,0.084020,1.000000,-0.283907,0.736349,-0.768775,0.602960,0.657875,0.154693,-0.382202,0.622209,-0.434271
RM,0.061728,-0.205928,0.290127,-0.396865,0.091267,-0.283907,1.000000,-0.198918,0.171596,-0.190030,-0.277064,-0.336408,0.120518,-0.634758,0.721489
AGE,-0.031016,0.353379,-0.554214,0.631742,0.083314,0.736349,-0.198918,1.000000,-0.750408,0.457339,0.499478,0.234894,-0.274650,0.593788,-0.354106
DIS,0.010385,-0.376323,0.659949,-0.695199,-0.102016,-0.768775,0.171596,-0.750408,1.000000,-0.492090,-0.520442,-0.185938,0.274036,-0.503383,0.235087
RAD,-0.031669,0.618538,-0.301067,0.608088,-0.023792,0.602960,-0.190030,0.457339,-0.492090,1.000000,0.911103,0.458930,-0.395845,0.503532,-0.386922
TAX,-0.007460,0.577501,-0.300221,0.731619,-0.045183,0.657875,-0.277064,0.499478,-0.520442,0.911103,1.000000,0.450978,-0.400353,0.552239,-0.479308
PTRATIO,0.056734,0.284967,-0.369974,0.370383,-0.137556,0.154693,-0.336408,0.234894,-0.185938,0.458930,0.450978,1.000000,-0.155939,0.352839,-0.495904
B,-0.030764,-0.357581,0.161515,-0.338007,0.040732,-0.382202,0.120518,-0.274650,0.274036,-0.395845,-0.400353,-0.155939,1.000000,-0.343821,0.317910
LSTAT,-0.019382,0.442743,-0.402116,0.624374,-0.055326,0.622209,-0.634758,0.593788,-0.503383,0.503532,0.552239,0.352839,-0.343821,1.000000,-0.725281
MEDV,0.006956,-0.393693,0.336805,-0.502898,0.182096,-0.434271,0.721489,-0.354106,0.235087,-0.386922,-0.479308,-0.495904,0.317910,-0.725281,1.000000

In [28]:
df.head(1)

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0,0.95577,0.0,8.14,0,0.538,6.047,88.8,4.4534,4,307.0,21.0,306.38,17.28,14.8

In [29]:
X = df[["CRIM","ZN","INDUS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT"]]
y = df["MEDV"]

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 5)

In [30]:
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression() 
regressor.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = regressor.predict(X_test) 
y_pred

array([12.31313793, 20.52057024, 30.45998352,  6.43497799, 22.97818212,
       24.63427751, 20.29010045, 19.53212939, 17.21166577, 15.97368788,
       27.20465998, 11.85867239, 15.58857045, 13.36355937, 22.55415033,
       22.63781932, 21.22394222, 19.79432621,  6.75076755, 30.74805224,
       18.58031152, 13.22197641, 19.9542162 , 40.52678854, 25.7957867 ,
       19.46457524, 29.21928687, 33.08701197, 17.41091617, 21.08758031,
       34.75339301, 27.18904554, 18.03058507, 10.63244498, 22.47499162,
       21.5913824 , 30.07573681, 13.31784435, 43.72567436, 17.61676167,
       13.21579552, 11.95938302, 19.54163517, 19.08129212, 24.90838083,
       13.2884262 , 27.41625091, 22.75126371, 25.07093356, 21.42580379,
       24.38691462, 20.67961168, 23.09176088, 18.61647049, 33.0012534 ,
       25.53548426, 18.94101872, 20.12179693, 36.57231   , 31.70131748,
       27.60989973, 42.69562718, 15.47815807, 22.71097419, 20.92766262,
       18.06608596, 30.60212841, 14.39361524, 34.31818223, 20.26190931,
       19.62150841, 25.48255033, 11.43260204, 19.81069902, 23.29628459,
       38.8359442 , 17.01877794, 16.26058234, 10.44573484, 17.20535832])

In [32]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1.head()

     Actual  Predicted
218     6.3  12.313138
191    20.1  20.520570
117    32.9  30.459984
50      8.4   6.434978
348    26.6  22.978182

In [33]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred))

R2- SCORE: 0.689447702649461

Lasso Regression

In [34]:
from sklearn.linear_model import Lasso

In [35]:
Lasso_Reg = Lasso() 
Lasso_Reg.fit(X_train, y_train)

Lasso()

In [36]:
y_pred1 = Lasso_Reg.predict(X_test) 
y_pred1

array([ 9.38739997, 21.34699851, 28.7710011 ,  3.77335563, 24.18275551,
       24.71540861, 19.68743953, 22.97654057, 18.64155152, 16.39098507,
       26.70723159, 12.30912829, 22.92827079, 18.46538953, 23.2045694 ,
       21.63037083, 20.81262002, 19.20731752,  7.30799424, 29.84869998,
       17.31863586, 11.63468024, 20.93743066, 35.38274205, 25.07060336,
       18.96669259, 29.39525633, 29.82587369, 19.12298652, 19.73614548,
       34.893626  , 27.3714154 , 19.50711484, 12.24276797, 26.08426428,
       23.94292688, 28.94004727, 14.75815234, 38.38941493, 19.14903874,
       14.23725119, 14.01274393, 18.96368251, 19.30423022, 26.32412575,
       13.40638866, 28.68376526, 22.96331382, 26.01533183, 23.95352361,
       24.90841877, 23.49724485, 24.08728196, 18.50392357, 29.85055273,
       24.5796968 , 20.26093067, 19.51659462, 31.70480291, 30.31160028,
       28.90014273, 37.6598702 , 16.66025262, 24.51320012, 21.30555045,
       18.39320885, 30.48666022, 13.72371699, 33.09326768, 23.45832135,
       17.11033493, 26.05994451,  9.9481714 , 20.98812265, 22.09433054,
       35.14333433, 16.19528588, 15.35546032, 12.80385487, 18.65059528])

In [37]:
df2 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred1})
df2.head()

     Actual  Predicted
218     6.3   9.387400
191    20.1  21.346999
117    32.9  28.771001
50      8.4   3.773356
348    26.6  24.182756

In [38]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred1))

R2- SCORE: 0.681604262038207

Ridge Regression

In [39]:
from sklearn.linear_model import Ridge
Ridge_Reg = Ridge()
Ridge_Reg.fit(X_train, y_train)

Ridge()

In [40]:
y_pred2 = Ridge_Reg.predict(X_test) 
y_pred2

array([12.37725731, 20.53811824, 30.55612508,  6.60007478, 23.59892962,
       24.56778129, 19.81042239, 20.13741075, 17.7034618 , 16.01801622,
       27.05100415, 12.30738892, 17.34127239, 13.89585533, 22.02276155,
       21.74857845, 20.71076493, 19.83393369,  6.60017892, 30.26617348,
       18.72603604, 13.27533569, 20.13070464, 40.08641772, 25.88699664,
       18.79937161, 28.98536486, 32.43604791, 17.70462598, 20.56467754,
       35.06368755, 26.78070833, 18.24942609,  9.86956659, 23.46090783,
       21.74551422, 29.86978546, 13.48762662, 43.29886899, 18.08802372,
       13.87674652, 12.37297972, 20.0192726 , 18.74203834, 25.22267043,
       13.39436117, 27.77519649, 22.33623843, 25.28319447, 22.06479531,
       24.1118413 , 21.23041491, 22.9158803 , 18.16814769, 32.33966011,
       25.34646936, 19.26510842, 19.77496581, 37.33166136, 31.46570748,
       27.02178105, 42.28556265, 15.62120795, 22.98246205, 20.88249403,
       17.85618828, 30.76231012, 14.27634158, 34.03147881, 20.94788986,
       19.55686152, 25.16264676, 10.46427003, 20.53570477, 22.57089799,
       38.49689416, 16.9645559 , 16.57710021, 11.79878175, 18.15768278])

In [41]:
df3 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred2})
df3.head()

     Actual  Predicted
218     6.3  12.377257
191    20.1  20.538118
117    32.9  30.556125
50      8.4   6.600075
348    26.6  23.598930

In [42]:
from sklearn import metrics 
print('R2- SCORE:', metrics.r2_score(y_test,y_pred2))

R2- SCORE: 0.6865090873179392

Cross-Validation

In [43]:
from sklearn.model_selection import cross_validate
regressor = LinearRegression(normalize = True)

In [44]:
cv_results = cross_validate(regressor, X, y, cv=10, scoring = "r2")
cv_results['test_score'].mean()

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,

0.7129621597468583